# Generated by Django 4.0.1 on 2022-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ailson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='foto_projeto',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
